# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.133.100:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: vueblog
    password: vueblog
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
shiro-redis:
  enabled: true
  redis-manager:
    host: 192.168.133.100:7379